name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN_PROD }}

    steps:
      - uses: actions/checkout@v1

      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, '/main') == false
        run: |
          echo "Tag is on ${{ github.event.base_ref }} not on main branch. No need to release. Goodbye!"
          exit -1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt

      - name: Deploy the job
        run: |
          dbx deploy --environment=prod --jobs=demo-ide-multiws-cicd-run